name: ribbit_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: 3.0.3
  dart_frog: 1.0.0
  dart_jsonwebtoken: 2.14.0
  dotenv: 4.2.0
  get_it: 7.7.0
  injectable: 2.4.1
  json_annotation: 4.9.0
  json_serializable: 6.8.0
  orm: 4.1.0
  ribbit_middle_end:
    path: ../ribbit_middle_end

dev_dependencies:
  build_runner: 2.4.10
  injectable_generator: 2.6.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
