include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - '**.g.dart'
    - build/**
    - lib/src/prisma/generated/**
linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
