name: ribbit_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cupertino_icons: 1.0.6
  firebase_core: 2.31.1
  firebase_messaging: 14.9.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: 7.7.0
  injectable: 2.4.2
  intl: 0.19.0
  retrofit: 4.1.0

dev_dependencies:
  build_runner: 2.4.11
  flutter_lints: 3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: 2.6.1
  retrofit_generator: 8.1.0
  very_good_analysis: 5.1.0


flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
